### PR TITLE
Add lat and lon live textfields, and map resizing in config. Smaller bugfixes

### PR DESCRIPTION
**Pull request by BartlomiejSkwira**
- map resizing in config

```
field :lat, :map do
  map_width '600px'
  map_height '400px'
end
```
- adds :latitude, :longitude live text fields below map

### CODE REVIEW

**Comment by beyondthestory** [comment]
Hi!

Can you rebase your commits together, and rebase the whole lot against master so this pull request applies cleanly?

Thanks

Jason

**Comment by BartlomiejSkwira** [comment]
Hey
Actually there are no tests for these features :( I'll get back to rebase after I write at least some basic tests

**Comment by chrisbloom7** [comment]
Any update on this? Seems like a useful addition.

**Comment by BartlomiejSkwira** [comment]
OK, I think I have fraked up my repo, I was trying to rebase/squash the commits and I accidentally deleted some :cry:  ..... my noobishness (I was squashing for the 1st time) had backfired. Wonder If I can get them back

**Comment by chrisbloom7** [comment]
git reflog is your friend. You can rewind to almost any point in your git
history.

**Comment by BartlomiejSkwira** [comment]
Ok, so this branch https://github.com/BartlomiejSkwira/rails_admin_map_field/tree/pull_request_branch seems to have all of the stuff. Now what should I do:
git rebase -i HEAD~26 #the number of commits that are in this pull request
#in editor, pick first commit, squash the rest

Correct?

**Comment by chrisbloom7** [comment]
Checkout the section "Feature Development" at http://reinh.com/blog/2009/03/02/a-git-workflow-for-agile-teams.html for info on proper squashing/rebasing of feature branches.

**Pull request closed without merging**
